TRINO_TO_MYSQL = {
    'COALESCE': 'IFNULL',
    'SUBSTR': 'SUBSTRING',
    'OFFSET %d LIMIT %d': 'LIMIT %d, %d',
    'DATE_FORMAT': 'DATE_FORMAT',
    'CONCAT': 'CONCAT',
    'CURRENT_TIMESTAMP': 'NOW()',
    'CURRENT_DATE': 'CURDATE()',
    'CURRENT_TIME': 'CURTIME()',
    'UNIX_TIMESTAMP()': 'UNIX_TIMESTAMP()',
    'FROM_UNIXTIME': 'FROM_UNIXTIME',
    'DATE_DIFF': 'DATEDIFF',
    'TIMESTAMP_DIFF': 'TIMESTAMPDIFF',
    "EXTRACT\\(YEAR FROM\\s*([^)]+)\\)": "YEAR(\\1)",
    "EXTRACT\\(MONTH FROM\\s*([^)]+)\\)": "MONTH(\\1)",
    "EXTRACT\\(DAY FROM\\s*([^)]+)\\)": "DAY(\\1)",
    "EXTRACT\\(HOUR FROM\\s*([^)]+)\\)": "HOUR(\\1)",
    "EXTRACT\\(MINUTE FROM\\s*([^)]+)\\)": "MINUTE(\\1)",
    "EXTRACT\\(SECOND FROM\\s*([^)]+)\\)": "SECOND(\\1)",
}

TRINO_TO_DORIS = {
    'COALESCE': 'IFNULL',
    'SUBSTR': 'SUBSTR',
    'OFFSET %d LIMIT %d': 'LIMIT %d, %d',
    'DATE_FORMAT': 'DATE_FORMAT',
    'CONCAT': 'CONCAT',
    'CURRENT_TIMESTAMP': 'NOW()',
    'CURRENT_DATE': 'CURDATE()',
    'CURRENT_TIME': 'CURTIME()',
    'UNIX_TIMESTAMP()': 'UNIX_TIMESTAMP()',
    'FROM_UNIXTIME': 'FROM_UNIXTIME',
    'DATE_DIFF': 'DATEDIFF',
    'TIMESTAMP_DIFF': 'TIMESTAMPDIFF',
    "EXTRACT\\(YEAR FROM\\s*([^)]+)\\)": "YEAR(\\1)",
    "EXTRACT\\(MONTH FROM\\s*([^)]+)\\)": "MONTH(\\1)",
    "EXTRACT\\(DAY FROM\\s*([^)]+)\\)": "DAY(\\1)",
    "EXTRACT\\(HOUR FROM\\s*([^)]+)\\)": "HOUR(\\1)",
    "EXTRACT\\(MINUTE FROM\\s*([^)]+)\\)": "MINUTE(\\1)",
    "EXTRACT\\(SECOND FROM\\s*([^)]+)\\)": "SECOND(\\1)",
}